[package]
name = "pi-sender"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { workspace = true }
bincode = { workspace = true }
shared = { path = "../shared" }
tracing = "0.1.41"
tracing-subscriber = "0.3.19"