[package]
name = "codec"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.100"
image = "0.25.8"
serde = { version = "1.0.228", features = ["derive"] }
strum_macros = "0.27.2"
webp = "0.3.1"
mozjpeg = "0.10"