[package]
name = "jetson-receiver"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { workspace = true }
shared = { path = "../shared" }
log = "0.4.27"
env_logger = "0.11.8"
anyhow = "1.0.99"
