[package]
name = "shared"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
bincode = "1.3"
tokio = { version = "1.0", features = ["full"] }
serde_json = "1.0.140"
log = "0.4.27"
once_cell = "1.21.3"
anyhow = "1.0.98"
tracing = "0.1.41"