[package]
name = "controller"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { workspace = true }
shared = { path = "../shared" }
csv = "1.3"
chrono = "0.4.41"
tracing = "0.1.41"
tracing-subscriber = "0.3.19"
