[package]
name = "controller"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { workspace = true }
shared = { path = "../shared" }
csv = "1.3"
log = "0.4.27"
env_logger = "0.11.8"
chrono = "0.4.41"
